#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Estalysis                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : FREE                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Accurate prediction for house values
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : DreamKatchr                              
your_link                                 :                  
your_city                                 : Hà Nội                                
email_address                             : tranghoang200
facebook_username                         : tranghoang200                                          
instagram_username                        : 
twitter_username                          : 
github_username                           : tranghoang200
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Search House And Properties
    description                           : Using google API and the crawled data from some biggest real estate website in Vietnam.
    fontawesome_icon_name                 : magic
    
  - title                                 : User friendly Mobile App
    description                           : Everything you need to know about real estate is in your phone.
    fontawesome_icon_name                 : mobile

  - title                                 : Graph Support Prediction
    description                           : Prediction with high tendency, and easy visual with graph.
    fontawesome_icon_name                 : play-circle

  - title                                 : Predict According To Hourse Type
    description                           : Type in the address you want, the app will predict all type of house in that area.
    fontawesome_icon_name                 : star

  - title                                 : Predict Specific House
    description                           : Input the infomation of the house you want, the app will predict all the house that have similar attribute.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Automatic Update Data Each Day
    description                           : You will be up to date immediately each day, convenience for precise analysis for real estate companies.
    fontawesome_icon_name                 : sync

  - title                                 : #Smart App Banner
    description                           : #Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : #arrow-alt-circle-down

  - title                                 : #Social Links
    description                           : #Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #link

  - title                                 : #FontAwesome Support
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
